import contributors from "public/data/json/contributors.json";
const undertakingCredits = `Generated by the ACM-X Undertaking Generator v0.3.0
Copyright FEU Tech ACM Student Chapter. All rights reserved.

Contributors:
${contributors.map((contributor) => {
    return `${contributor.name}, ${contributor.position}\n${contributor.linkedin}`;
}).join("\n\n")}

For further information, please contact us at <acm.feu.it@gmail.com>`;

export default undertakingCredits;