jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
    timeout-minutes: 2

name: Commitlint
on: [push, pull_request]
